pull_request_rules:
- name: Automatically merge Scala Steward PRs on CI success
  conditions:
  - author=scala-steward
  - body~=labels:.*semver-patch.*
  - status-success="Test CE2 2_12 (jvm)"
  - status-success="Test CE3 2_12 (jvm)"
  - status-success="Test CE2 2_13 (jvm)"
  - status-success="Test CE3 2_13 (jvm)"
  - status-success="Test CE3 2_13 (js)"
  - status-success="Test CE3 3_0 (jvm)"
  - status-success="Test CE3 3_0 (js)"
  actions:
    merge:
      method: merge
