pull_request_rules:
  - name: Automatically approve/merge Scala Steward PRs on CI success
    conditions:
      - author=scala-steward
      - status-success="build-success-checkpoint"
      - body~=labels:.*semver-spec-patch
    actions:
      review:
        type: APPROVE
        message: Automatically approving scala-steward
      merge:
        method: merge
