pull_request_rules:
  - name: Automatically approve/merge Scala Steward PRs on CI success
    conditions:
      - author=scala-steward
      - check-success="build-success-checkpoint"
      - body~=labels:.*semver-spec-patch
    actions:
      review:
        type: APPROVE
        message: Automatically approving scala-steward
      merge:
        method: merge

  - name: forward-port labeled PRs to the 0.19 branch
    conditions:
      - label="forwardport-0.19"
    actions:
      backport:
        branches:
          - "series/0.19"

  - name: automatically merge forward-port if the pass tests
    conditions:
      - author=mergify[bot]
      - head~=^mergify/bp/
      - base="series/0.19"
      - check-success="build-success-checkpoint"
    actions:
      merge:
        method: merge
