import sbt._
import scala.jdk.CollectionConverters._
import scala.io.Source
import scala.util.Using
import software.amazon.smithy.model.node.{Node, ObjectNode}

object AwsBoilerplate {

  private lazy val cachedServiceVersions: Map[String, String] =
    fetchServiceVersions()

  def generateSources(sourceDir: java.io.File): File = {
    val sortedServices = cachedServiceVersions.toList.sortBy(_._1)
    writeSpecs(sourceDir, sortedServices)
  }

  def generateResources(resourceDir: java.io.File): File = {
    val sortedServices = cachedServiceVersions.toList.sortBy(_._1)
    val protocols = resolveProtocols(sortedServices, resourceDir)
    writeMetadata(resourceDir, sortedServices, protocols)
  }

  private def writeSpecs(
      sourceDir: java.io.File,
      sortedServices: List[(String, String)]
  ): File = {
    val thisYear = java.time.OffsetDateTime.now().getYear()
    val copyright =
      s"""/*
         | *  Copyright 2021-$thisYear Disney Streaming
         | *
         | *  Licensed under the Tomorrow Open Source Technology License, Version 1.0 (the "License");
         | *  you may not use this file except in compliance with the License.
         | *  You may obtain a copy of the License at
         | *
         | *     https://disneystreaming.github.io/TOST-1.0.txt
         | *
         | *  Unless required by applicable law or agreed to in writing, software
         | *  distributed under the License is distributed on an "AS IS" BASIS,
         | *  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
         | *  See the License for the specific language governing permissions and
         | *  limitations under the License.
         | */
         |""".stripMargin

    val serviceValues = sortedServices.map { case (name, version) =>
      s"""  val ${toCamelCase(name)} = ("$name", "$version")"""
    }

    val content =
      s"""|$copyright
          |// Auto-generated by AwsBoilerplate — DO NOT EDIT
          |// Versions sourced from: software.amazon.api.models:all BOM (Maven Central)
          |//
          |// Each value is a (artifactName, version) tuple for use with:
          |//   smithy4sAwsSpecEntries ++= Seq(AWS.dynamodb)
          |// For backward compat, use:
          |//   smithy4sAwsSpecs ++= Seq("dynamodb")
          |// which resolves to: "software.amazon.api.models" % "dynamodb" % "1.0.11"
          |
          |package smithy4s.codegen
          |
          |object AwsSpecs {
          |  val org = "software.amazon.api.models"
          |  val bomVersion = "${Dependencies.AwsModels.bomVersion}"
          |
          |${serviceValues.mkString(System.lineSeparator())}
          |}
          |""".stripMargin

    val target = sourceDir / "smithy4s" / "codegen" / "AwsSpecs.scala"
    sbt.IO.write(target, content)
    target
  }

  private def writeMetadata(
      resourceDir: java.io.File,
      sortedServices: List[(String, String)],
      protocols: Map[String, String]
  ): File = {
    val entries = sortedServices.map { case (name, version) =>
      val protocol = protocols.getOrElse(name, "unknown")
      ObjectNode
        .builder()
        .withMember("name", name)
        .withMember("version", version)
        .withMember("protocol", protocol)
        .build()
    }

    val servicesArray = Node.arrayNode(entries: _*)
    val root = ObjectNode
      .builder()
      .withMember("services", servicesArray)
      .build()

    val content = Node.prettyPrintJson(root)

    val target = resourceDir / "aws-service-metadata.json"
    sbt.IO.write(target, content)
    target
  }

  private def fetchServiceVersions(): Map[String, String] = {
    val bomFiles = coursierapi.Fetch
      .create()
      .addDependencies(
        coursierapi.Dependency.of(
          Dependencies.AwsModels.org,
          "all",
          Dependencies.AwsModels.bomVersion
        )
      )
      .addArtifactTypes("pom")
      .fetch()
      .asScala
      .toList

    val pomFile = bomFiles.find(_.getName.endsWith(".pom")).getOrElse {
      throw new MessageOnlyException(
        "Failed to resolve AWS models BOM POM from Maven Central"
      )
    }

    val dbFactory = javax.xml.parsers.DocumentBuilderFactory.newInstance()
    dbFactory.setNamespaceAware(true)
    val doc = dbFactory.newDocumentBuilder().parse(pomFile)
    doc.getDocumentElement().normalize()
    val pomNs = "http://maven.apache.org/POM/4.0.0"

    val dmList = doc.getElementsByTagNameNS(pomNs, "dependencyManagement")
    if (dmList.getLength == 0) Map.empty[String, String]
    else {
      val dm = dmList.item(0).asInstanceOf[org.w3c.dom.Element]
      val depList = dm.getElementsByTagNameNS(pomNs, "dependency")
      (0 until depList.getLength).map { i =>
        val dep = depList.item(i).asInstanceOf[org.w3c.dom.Element]
        val artifactId =
          dep.getElementsByTagNameNS(pomNs, "artifactId").item(0).getTextContent
        val version =
          dep.getElementsByTagNameNS(pomNs, "version").item(0).getTextContent
        (artifactId, version)
      }.toMap
    }
  }

  private def resolveProtocols(
      services: List[(String, String)],
      cacheDir: java.io.File
  ): Map[String, String] = {
    val cacheFile = new java.io.File(cacheDir, ".aws-protocol-cache")
    readProtocolCache(cacheFile) match {
      case Some(protocols) => protocols
      case None =>
        val protocols = resolveProtocolsFromJars(services)
        writeProtocolCache(cacheFile, protocols)
        protocols
    }
  }

  private def resolveProtocolsFromJars(
      services: List[(String, String)]
  ): Map[String, String] = {
    val protocolKeys = List(
      "aws.protocols#restJson1" -> "restJson1",
      "aws.protocols#restXml" -> "restXml",
      "aws.protocols#awsJson1_0" -> "awsJson1_0",
      "aws.protocols#awsJson1_1" -> "awsJson1_1",
      "aws.protocols#awsQuery" -> "awsQuery",
      "aws.protocols#ec2Query" -> "ec2Query"
    )

    services.map { case (name, version) =>
      val protocol = resolveServiceJar(name, version) match {
        case Some(jar) => detectProtocol(jar, protocolKeys)
        case None      => "unknown"
      }
      (name, protocol)
    }.toMap
  }

  /** Resolve the service model JAR for a single AWS service.
    * Each service resolves independently so a missing artifact
    * doesn't prevent other services from being detected.
    */
  private def resolveServiceJar(
      name: String,
      version: String
  ): Option[java.io.File] = {
    try {
      val jars = coursierapi.Fetch
        .create()
        .addDependencies(
          coursierapi.Dependency.of(Dependencies.AwsModels.org, name, version)
        )
        .fetch()
        .asScala
        .toList
      // The service's own JAR contains the artifact name as its filename prefix.
      // Transitive deps (smithy-aws-traits, etc.) have different prefixes, so matching
      // within this per-service scope is unambiguous.
      jars.find { jar =>
        val fileName = jar.getName
        fileName.startsWith(name + "-") || fileName.startsWith(
          name.replace('-', '_') + "-"
        )
      }
    } catch {
      case e: Exception =>
        System.err.println(
          s"[smithy4s] Warning: failed to resolve AWS model $name:$version: ${e.getMessage}"
        )
        None
    }
  }

  private def readProtocolCache(
      cacheFile: java.io.File
  ): Option[Map[String, String]] = {
    if (!cacheFile.exists()) None
    else
      Using(Source.fromFile(cacheFile)) { source =>
        val lines = source.getLines().toList
        val cachedVersion = lines.headOption.getOrElse("")
        if (cachedVersion != Dependencies.AwsModels.bomVersion) None
        else
          Some(
            lines.tail
              .filter(_.contains("="))
              .map { line =>
                val idx = line.indexOf('=')
                (line.substring(0, idx), line.substring(idx + 1))
              }
              .toMap
          )
      }.toOption.flatten
  }

  private def writeProtocolCache(
      cacheFile: java.io.File,
      protocols: Map[String, String]
  ): Unit = {
    val header = Dependencies.AwsModels.bomVersion
    val entries = protocols.toSeq.sortBy(_._1).map { case (name, protocol) =>
      s"$name=$protocol"
    }
    val content = s"$header\n${entries.mkString("\n")}\n"
    cacheFile.getParentFile.mkdirs()
    sbt.IO.write(cacheFile, content)
  }

  private def detectProtocol(
      jar: java.io.File,
      protocolKeys: List[(String, String)]
  ): String = {
    Using.resource(new java.util.zip.ZipFile(jar)) { zipFile =>
      val smithyEntries = zipFile.entries().asScala.toList.filter { entry =>
        val name = entry.getName
        name.startsWith("META-INF/smithy/") &&
        name.endsWith(".json") &&
        !name.contains("manifest")
      }

      protocolKeys
        .find { case (key, _) =>
          smithyEntries.exists { entry =>
            Using.resource(zipFile.getInputStream(entry)) { is =>
              Source.fromInputStream(is, "UTF-8").mkString.contains(key)
            }
          }
        }
        .map(_._2)
        .getOrElse("unknown")
    }
  }

  private def toCamelCase(str: String): String = {
    str.split('-').toList match {
      case head :: tl => (head :: tl.map(_.capitalize)).mkString
      case Nil        => ""
    }
  }

}
