handlers = java.util.logging.ConsoleHandler
java.util.logging.ConsoleHandler.level = ALL
software.amazon.smithy.openapi.fromsmithy.mappers.RemoveUnusedComponents.level = SEVERE
software.amazon.smithy.openapi.fromsmithy.mappers.UnsupportedTraits.level = SEVERE
